version: '3.5'

services:
    elasticsearch:
        image: elasticsearch:7.16.2
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "xpack.security.enabled=false"
        ports:
            - '9200:9200'
        networks:
            - observability-network
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.16.2
        container_name: kibana
        hostname: kibana
        ports:
            - '5601:5601'
        networks:
            - observability-network
        environment:
            - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
        depends_on:
            - elasticsearch

networks:
    observability-network:
        external: true

volumes:
    elasticsearch-data:
        driver: local